MQTT_BROKER = "broker.hivemq.com"
MQTT_PORT = 8883

TOPIC_PREFIX = "nws7D1IJ"
COUNTRY = "sa"
REGION = "ep"
CITY = "dammam"
DISTRICT = "al-faisaliyah"
CAMERA_ID = 1
EVENT_TYPE = "accident"

MQTT_TOPIC = f"{TOPIC_PREFIX}/{COUNTRY}/{REGION}/{CITY}/{DISTRICT}/{CAMERA_ID}/{EVENT_TYPE}"
MQTT_CLIENT_ID = f"cam_{CITY}_{DISTRICT}_{CAMERA_ID}"

ALERT_COOLDOWN_SECONDS = 10

ENGINE_PATH = "accident_detection_model32.engine"
INPUT_SHAPE = (1, 128, 128, 1)
DETECTION_THRESHOLD = 0.5
SMOOTHING_WINDOW = 15
